feat: fedev personal page
BuidlGuidl/batch9.buidlguidl.com pull request #13
Opened 2024-09-11 00:10 UTC by fedeloterstein

## Description

EN este PR se trabajo en: 
- Crear la carpeta builders
- Creación de mi pagina personal
- Soporte para dark mode. 

 
<img width="1706" alt="Captura de pantalla 2024-09-10 a la(s) 21 07 09" src="https://github.com/user-attachments/assets/760e052e-d8aa-4548-8113-f490893e9a6d">
<img width="1706" alt="Captura de pantalla 2024-09-10 a la(s) 21 07 21" src="https://github.com/user-attachments/assets/8a5ffa83-01a6-45bb-bb77-45f169df6bd9">

## Additional Information

- [x] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [x] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

## Related Issues

_Closes #9 

_Note: If your changes are small and straightforward, you may skip the creation of an issue beforehand and remove this section. However, for medium-to-large changes, it is recommended to have an open issue for discussion and approval prior to submitting a pull request._

Your ENS/address: 0xDFbE6c0A54F9f4f758753aE56eDD02Dd92C29be3

2024-09-12 13:31 UTC, phipsae requested changes
@fedeloterstein, great job on the clean and well-organized code for your personal page! 

Just a small suggestion—consider adding a personal touch, like a picture (it doesn’t necessarily have to be of you), to make it stand out even more.

I've also left a minor comment below.

2024-09-13 03:33 UTC, fedeloterstein commented on packages/nextjs/contracts/deployedContracts.ts
> +const deployedContracts = {
I already corrected it.

2024-09-13 03:46 UTC, fedeloterstein commented
> @fedeloterstein, great job on the clean and well-organized code for your personal page!
> 
> Just a small suggestion—consider adding a personal touch, like a picture (it doesn’t necessarily have to be of you), to make it stand out even more.
> 
> I've also left a minor comment below.

I've already made an update. I liked this way of keeping a clean profile, not so overloaded. Sometimes less is more. 
<img width="1710" alt="Captura de pantalla 2024-09-13 a la(s) 00 44 55" src="https://github.com/user-attachments/assets/14c74385-5958-49d8-9a79-ae86984e1dc6">

2024-09-13 05:57 UTC, phipsae commented
> > @fedeloterstein, great job on the clean and well-organized code for your personal page!
> > Just a small suggestion—consider adding a personal touch, like a picture (it doesn’t necessarily have to be of you), to make it stand out even more.
> > I've also left a minor comment below.
> 
> I've already made an update. I liked this way of keeping a clean profile, not so overloaded. Sometimes less is more. <img alt="Captura de pantalla 2024-09-13 a la(s) 00 44 55" width="1710" src="https://private-user-images.githubusercontent.com/76790873/367141930-14c74385-5958-49d8-9a79-ae86984e1dc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMDY4MzYsIm5iZiI6MTcyNjIwNjUzNiwicGF0aCI6Ii83Njc5MDg3My8zNjcxNDE5MzAtMTRjNzQzODUtNTk1OC00OWQ4LTlhNzktYWU4Njk4NGUxZGM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDA1NDg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4YjFjMTM4OGI1MmY1YjNkZjE5ZWVlMGNiNGRhNmRhYTUwYTI3ZjBmNzU1YTk2YTA1YzdkZDk3NjA0MzdmNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0Z03hEunw0-z0RrgRbX9_nLMCg8hysogvxZ3FDvfHfg">

Thanks! I agree on that :) 

Merged.

2024-09-13 05:58 UTC, merged